### ISSUE TITLE
03_10問題

### ISSUE THREAD

**Issue by kannayuu** [kannayuu/30seconds_list#2]
## Using flexbox, create a 3-column layout where each column takes up a col-{n} / 12 ratio of the container.

> 如何使用flex 達到下面的分配的項目

``` html
<div class="row">
  <div class="col-2"></div>
  <div class="col-7"></div>
  <div class="col-3"></div>
</div>
```
>利用flex-grow 屬性去分配大小

```css
.row{
  display:flex
}
.col-2 {
  flex-grow:2;
}
.col-7 {
  flex-grow:7;
}
.col-3 {
  flex-grow:3;
}
```

##  Can a web page contain multiple(多) <header> elements? What about <footer> elements?

> 基本上是允許有多個狀態
> 基本上建議每個章節允許只有一個狀況
