### ISSUE TITLE
03_21＿css__01

### ISSUE THREAD

**Issue by kannayuu** [kannayuu/30seconds_list#7]
## Box-sizing reset
重置核模型 讓寬高不會受到線匡跟內部的padding去影響到

> box-sizing: inherit makes an element respect its parent's box-sizing rule.
> 這一段說明是表示已父層 box-sizing rule 去作為繼承 

## Clearfix 
元素做完浮動要清除是避免父曾抓不到子層高度坍塌狀況出現

比較常用方法
在複層後面坐上偽元素去讓他抓到子層的高度

```html
<div class="item__list">
  <div class="item">float a</div>
  <div class="item">float b</div>
  <div class="item">float c</div>
  <div class="clearfix"></div>
</div>
```

> 如果沒用偽元素通常會使用 clearfix 利用clear both 去抓到高度
>> 用偽元素 會少掉一個tag 下面有範例使用狀況
```css
.item__list::after {
  content: '';
  display: block;
  clear: both;
}
```
