### ISSUE TITLE
03_22_css_2

### ISSUE THREAD

**Issue by kannayuu** [kannayuu/30seconds_list#8]
## Button border animation
按鈕底部的線自動會生出來
```html
<div class="button-border">
   <button class="button">Submit</button>
   <!--使用button主要他是內聯元素-->  
</div>
```
```css
.button {
  background-color: #c47135;
  border: none;
  color: #ffffff;
  outline: none;
  padding: 12px 40px 10px;
  position: relative;
}
.button:before,
.button:after {
  border: 0 solid transparent;
  //transparent <= 代表背景顏色為透明
  transition: all 0.25s;
  content: '';
  height: 24px;
  position: absolute;
  width: 24px;
}
.button:before {
  border-top: 2px solid #c47135;
  left: 0px;
  top: -5px;
}
.button:after {
  border-bottom: 2px solid #c47135;
  bottom: -5px;
  right: 0px;
}
.button:hover {
  background-color: #c47135;
}
.button:hover:before,
.button:hover:after {
  height: 100%;
  width: 100%;
 //利用觸碰到自動長寬度跟高度
}
```

## Calc()
[參考網址](https://ithelp.ithome.com.tw/articles/10130065)
主要這樣在RWD可以方便比例換算
